name: LiteEconomy
version: ${project.version}
main: co.ignitus.liteeconomy.LiteEconomy
api-version: "1.13"
authors: ["Ignitus Co"]
description: Simple economy plugin that provides an extra economy or allows balances to be shared across servers.
website: https://ignitus.co/
softdepend: [Vault, PlaceholderAPI, Essentials]

commands:
  liteeconomy:
    description: Manage players balances.
  money:
    aliases: [balance]

permissions:
  liteeconomy.give:
    description: Grants access to /liteeconomy give
  liteeconomy.set:
    description: Grants access to /liteeconomy set
  liteeconomy.take:
    description: Grants access to /liteeconomy take
  liteeconomy.pay:
    description: Grants access to /liteeconomy pay
  liteeconomy.money:
    description: Grants access to /money
    default: true
  liteeconomy.money.others:
    description: Grants access to /money [user]
    default: true
  liteeconomy.convert:
    description: Grants access to /liteeconomy convert
  liteeconomy.baltop:
    default: true
    description: Grants access to /liteeconomy baltop